CREATE DATABASE IF NOT EXISTS moto;

USE moto;

CREATE TABLE IF NOT EXISTS moto (
    id INT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(30) NOT NULL,
    model VARCHAR(30) NOT NULL,
    type VARCHAR(30) UNIQUE,
    price FLOAT NOT NULL,
    image TEXT NOT NULL
);